[workspace]
resolver = "3"
members = [
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Suberlin Sinaga<suberlinsinaga@gmail.com>"]

[workspace.dependencies]
argus = { git = "ssh://git@github.com/saians07/argus.git", branch = "master" , features = ["errors", "logs"]}
async-trait = "0.1.92"
anyhow = "1.0.104"
serde = "1.0.229"
rust_decimal = "1.42.1"
reqwest = { version = "0.13.4", features = ["json"] }
serde_qs = "1.1.3"
serde_json = "1.0.151"
hmac = "0.13.0"
hex = "0.4.3"
sha2 = "0.11.0"
chrono = { version = "0.4.45", features = ["serde"] }
secrecy = { version = "0.10.3", features = ["serde"] }
polars = { version = "0.54.4", features = ["lazy", "json", "dtype-decimal", "diff", "abs", "strings"] }
