[package]
name = "indodax"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
hydra_core = { path = "../hydra_core" }
async-trait = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
argus = { workspace = true }
serde_qs = { workspace = true }
chrono = { workspace = true }
secrecy = { workspace = true }
rust_decimal = { workspace = true }
serde_json = { workspace = true }
