[package]
name = "hydra"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
anyhow = { workspace = true }
serde = { workspace = true }
rust_decimal = { workspace = true }
reqwest = { workspace = true }
argus = { workspace = true }
hydra_core = { path = "../hydra_core" }
indodax = { path = "../indodax", optional = true }

[features]
indodax = ["dep:indodax"]
